language: cpp
dist: trusty
osx_image: xcode7.3
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
sudo: required


matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
  include:
    - os: linux
      env: GCC_VERSION=5
      compiler: gcc
    - os: linux
      env: GCC_VERSION=6
      compiler: gcc

cache:
  directories:
  - ${HOME}/OpenCV
  - ${HOME}/igl
  - ${HOME}/glfw3

addons: &gcc5
  apt:
    packages:
      - g++-5
      - gcc-5
      - gcc-6
      - g++-6
      - libeigen3-dev 
      - libboost-all-dev
    sources:
      - ubuntu-toolchain-r-test
before_install:
  - if [ $TRAVIS_OS_NAME = "linux" ]; then
      mkdir -p include;
      curl -o include/catch.hpp https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp;
      wget -O half.zip http://sourceforge.net/projects/half/files/latest/download;
      unzip -q half.zip;
      cp half-1.11.0/include/half.hpp include/half.hpp;
      sudo apt-get update -q;
      sudo apt-get -y install opencl-headers ocl-icd-opencl-dev libdc1394-22-dev libavcodec-dev libavformat-dev libswscale-dev libtheora-dev libvorbis-dev libxvidcore-dev libx264-dev yasm libopencore-amrnb-dev libopencore-amrwb-dev libv4l-dev libxine2-dev zlib1g-dev libjpeg-dev libwebp-dev libpng-dev libtiff5-dev libjasper-dev libopenexr-dev libgdal-dev qt5-default libvtk6-dev libtbb-dev libgtk-3-dev libglew-dev libglu1-mesa-dev xorg-dev;
      git clone https://github.com/boostorg/compute.git;
      sudo cp -r ./compute/include/boost/* /usr/include/boost;
      bash .travis/amd_sdk.sh;
      tar -xjf AMD-SDK.tar.bz2;
      AMDAPPSDK=${HOME}/AMDAPPSDK;
      export OPENCL_VENDOR_PATH=${AMDAPPSDK}/etc/OpenCL/vendors;
      mkdir -p ${OPENCL_VENDOR_PATH};
      sh AMD-APP-SDK*.sh --tar -xf -C ${AMDAPPSDK};
      echo libamdocl64.so > ${OPENCL_VENDOR_PATH}/amdocl64.icd;
      export LD_LIBRARY_PATH=${AMDAPPSDK}/lib/x86_64:${LD_LIBRARY_PATH};
      chmod +x ${AMDAPPSDK}/bin/x86_64/clinfo;
      ${AMDAPPSDK}/bin/x86_64/clinfo;
      sudo rm /usr/bin/g++;
      sudo ln -s /usr/bin/g++-5 /usr/bin/g++;
      sudo ln -s /usr/include/eigen3/Eigen /usr/include/Eigen;
      cd ${HOME};
      pwd;
      mkdir -p OpenCV;
      cd OpenCV;
      if [ ! -e "3.1.0.zip" ]; then
        wget https://github.com/Itseez/opencv/archive/3.1.0.zip;
      fi;
      if [ ! -e "opencv-3.1.0" ]; then
        unzip -q 3.1.0.zip;
      fi;
      cd opencv-3.1.0;
      cmake .;
      make -j4;
      sudo make install;
      cd ${HOME};
      wget -O ippicv_linux_20141027.tgz https://sourceforge.net/projects/opencvlibrary/files/3rdparty/ippicv/ippicv_linux_20141027.tgz;
      tar -xzvf ippicv_linux_20141027.tgz;
      sudo cp ippicv_lnx/lib/intel64/* /usr/lib;
      cd ${TRAVIS_BUILD_DIR};
      if [ $GCC_VERSION = 6 ]; then
        sudo rm /usr/bin/g++;
        sudo ln -s /usr/bin/g++-6 /usr/bin/g++;
      fi;
      sudo ln -s /usr/include/eigen3/Eigen /usr/include/Eigen;
      cd ${HOME};
      mkdir -p igl;
      cd igl;
      if [ ! -e "master.zip" ]; then
        wget https://github.com/libigl/libigl/archive/master.zip;
      fi;
      if [ ! -e "libigl-master" ]; then
        unzip -q master.zip;
      fi;
      sudo cp -r libigl-master/include/* /usr/local/include;
      cd ${HOME};
      mkdir -p glfw3;
      cd glfw3;
      if [ ! -e "glfw-3.2.zip" ]; then
        wget https://github.com/glfw/glfw/releases/download/3.2/glfw-3.2.zip;
      fi;
      if [ ! -e "glfw-3.2" ]; then
        unzip -q glfw-3.2.zip;
      fi;
      cd glfw-3.2;
      cmake -DBUILD_SHARED_LIBS=ON .;
      make;
      sudo make install;
      cd ${HOME};
      wget -O glcorearb.h http://www.opengl.org/registry/api/GL/glcorearb.h;
      sudo mkdir -p /usr/include/GL;
      sudo cp glcorearb.h /usr/include/GL;
      cd ${TRAVIS_BUILD_DIR};
      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib;
    fi;

  - if [ $TRAVIS_OS_NAME = "osx" ]; then
      brew update;
      brew install eigen;
      brew install pkg-config;
      brew install boost;
      mkdir -p include;
      wget -O half.zip http://sourceforge.net/projects/half/files/latest/download;
      unzip -q half.zip;
      cp half-1.11.0/include/half.hpp include/half.hpp;
      git clone https://github.com/boostorg/compute.git;
      sudo cp -r ./compute/include/boost/* /usr/local/include/boost;
      git clone https://github.com/philsquared/Catch.git;
      sudo cp ./Catch/single_include/catch.hpp /usr/local/include;
      xcode-select --install;
      cd ${HOME};
      pwd;
      mkdir -p OpenCV;
      cd OpenCV;
      wget https://github.com/Itseez/opencv/archive/3.1.0.zip;
      unzip -q 3.1.0.zip;
      cd opencv-3.1.0;
      cmake .;
      make -j4;
      make install;
      cd ${HOME};
      mkdir -p igl;
      cd igl;
      if [ ! -e "master.zip" ]; then
        wget https://github.com/libigl/libigl/archive/master.zip;
      fi;
      if [ ! -e "libigl-master" ]; then
        unzip -q master.zip;
      fi;
      sudo cp -r libigl-master/include/* /usr/local/include;
      cd ${HOME};
      mkdir -p glfw3;
      cd glfw3;
      if [ ! -e "glfw-3.2.zip" ]; then
        wget https://github.com/glfw/glfw/releases/download/3.2/glfw-3.2.zip;
      fi;
      if [ ! -e "glfw-3.2" ]; then
        unzip -q glfw-3.2.zip;
      fi;
      cd glfw-3.2;
      cmake -DBUILD_SHARED_LIBS=ON .;
      make;
      sudo make install;
      cd ${HOME};
      wget -O ippicv_macosx_20141027.tgz https://sourceforge.net/projects/opencvlibrary/files/3rdparty/ippicv/ippicv_macosx_20141027.tgz/download;
      tar -xzvf ippicv_macosx_20141027.tgz;
      cp ippicv_osx/lib/* /usr/local/lib/;
      cd ${TRAVIS_BUILD_DIR};
      sudo ln -s /usr/local/include/eigen3/Eigen /usr/local/include/Eigen;
    fi;
    
script:
  - cmake . -DUSE_ADDRESS_SANITIZER=0
  - make VERBOSE=1 -j4
